WITH stg AS (
    SELECT * FROM {{ ref('stg_athlete_events') }}
)

SELECT DISTINCT
    MD5(NATIONALITY)            AS COUNTRY_SK,
    COUNTRY_NAME,
    NATIONALITY                 AS COUNTRY_CODE,
    COUNTRY_FIRST_PARTICIPATION
FROM stg
WHERE NATIONALITY IS NOT NULL