WITH stg AS (
    SELECT DISTINCT
        NATIONALITY,
        COUNTRY_TOTAL_GOLD,
        COUNTRY_TOTAL_MEDALS,
        COUNTRY_FIRST_PARTICIPATION,
        COUNTRY_BEST_RANK
    FROM {{ ref('stg_athlete_events') }}
    WHERE NATIONALITY IS NOT NULL
),

dim_country AS (
    SELECT * FROM {{ ref('dim_country') }}
)

SELECT
    ROW_NUMBER() OVER (ORDER BY co.COUNTRY_SK)  AS COUNTRY_PERFORMANCE_SK,
    co.COUNTRY_SK,
    s.COUNTRY_TOTAL_GOLD,
    s.COUNTRY_TOTAL_MEDALS,
    s.COUNTRY_FIRST_PARTICIPATION,
    s.COUNTRY_BEST_RANK
FROM stg s
LEFT JOIN dim_country co
    ON s.NATIONALITY = co.COUNTRY_CODE